# Generated by Django 5.0 on 2023-12-08 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=255)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('potencia_actual', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusDispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso_mantenimiento', models.DateTimeField(auto_now_add=True)),
                ('iddispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='statusDispositivoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusdispositivo'),
        ),
        migrations.CreateModel(
            name='Lecturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('potenciaActual', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('iddispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.dispositivo')),
                ('idtipodispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.tiposdispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipodispositivoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.tiposdispositivo'),
        ),
    ]
