# Generated by Django 5.0 on 2023-12-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_mantenimientos_fecha_salida_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientos',
            name='fecha_salida_mantenimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
